# Generated by Django 4.2.3 on 2023-07-23 20:39

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=product.models.upload_to)),
                ('category', models.CharField(choices=[('Coaches', 'Coache'), ('Beds', 'Bed'), ('Rugs', 'Rog')], default='Coaches', max_length=255)),
            ],
        ),
    ]
